name: Test Suite

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: "actions/checkout@v3"

      - uses: "actions/setup-python@v4"
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Code health checks
        run: |
          make check

      - name: Test and coverage checks
        run: |
          make covercli

      - name: Refresh coveralls
        if: github.event_name == 'push'
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          poetry run coveralls
